- name: Remove snap installed firefox package
  community.general.snap:
    name: firefox
    state: absent 

- name: Install Mozilla Firefox GPG Key
  ansible.builtin.get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: /etc/apt/keyrings/packages.mozilla.org.asc

- name: Install Mozilla Firefox APT Repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main
    state: present

- name: Install Mozilla PIN
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000

      Package: firefox*
      Pin: release o=Ubuntu
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/mozilla

- name: Install Mozilla Firefox
  ansible.builtin.apt:
    name: firefox
    cache_valid_time: 300

