- name: Install default packages
  ansible.builtin.apt:
    name:
      - build-essential
      - jq
      - tmux
      - curl
      - wget
      - htop
      - git
      - vim
      - python3-venv
      - python3-wheel
      - unzip
    cache_valid_time: 300


- name: Add Fish shell GPG Key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x88421E703EDC7AF54967DED473C9FCC9E2BB48DA
    dest: /etc/apt/keyrings/fish.asc

- name: Add Fish shell PPA Repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/fish.asc] https://ppa.launchpadcontent.net/fish-shell/release-4/ubuntu {{ ansible_distribution_release }} main  
    state: present

- name: Install fish shell
  ansible.builtin.apt:
    name:
      - fish
    cache_valid_time: 300

- name: Set sysctl settings
  ansible.posix.sysctl:
    name: 'vm.swappiness'
    value: '10'
  when: ansible_memtotal_mb >= 16384

